development:
  adapter: mysql2
  encoding: utf8
  database: grocery_store_development
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
test:
  adapter: mysql2
  encoding: utf8
  database: grocery_store_test
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
